apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: http
  #- port: 443
  #  protocol: TCP
  #  name: https
  selector:
    app: nginx
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: my-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      #volumes:
      #- name: secret-volume
      #  secret:
      #    secretName: nginxsecret
      containers:
      - name: nginxhttp
        image: nginx:latest
        ports:
        #- containerPort: 443
        - containerPort: 80
        #volumeMounts:
        #- mountPath: /etc/nginx/ssl
        #  name: secret-volume
